bot: 
    api_key: 1933129297:AAFtgv9LaOgDbT6fUKnIbd1rBsVCrIA_k2o
files:
    text: txt/tagged.txt
    pic_dir: pic
    users_list: users
font:
    font_file: font/Roboto-Bold.ttf
    font_size: 30
