bot: 
    api_key: API_KEY
database:
    file: dataBase/bazaDB.db
    content_table: content
    users_table: users
port_config:
    port_name: COM4
    baud: 9600
    content_send: g0.txt=
    author_send: t0.txt=

