bot: 
    api_key: 1933129297:AAFtgv9LaOgDbT6fUKnIbd1rBsVCrIA_k2o
database:
    file: dataBase/bazaDB.db
    content_table: content
    users_table: users
server_config:
    root_path: /txt
    port: 8081
    

